apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mineops-0
  namespace: argocd
spec:
  destination:
    namespace: mineops-0
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/mineops-0
    repoURL: git@github.com:kywa/kywa-argo.git
    targetRevision: haproxy-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
