apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  namespace: argocd
spec:
  destination:
    namespace: cluster-config
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/cluster
    repoURL: git@github.com:kywa/kywa-argo.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
